### ISSUE TITLE
Maybe combine this repo with railsbridge/docs?

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge-boston/docs-hardfork#48]
Hey Boston RailsBridge folks!

Would y'all be interested in exploring merging the railsbridge/docs with the railsbridge-boston/docs at some point?

It seems like the biggest split is in the Installfest — your VM-based approach vs the main curriculum's non-VM approach. It seems like there should be some way to present both of them and instruct students to use a particular one for a given workshop. Or we could split the Installfest out into a separate repo and then just share the curricula portion of the docs repo. Or do something else!

I imagine that part of the joy of maintaining a fork is that you get to control how quickly changes are merged in and deployed, so we'd want to add some of y'all as committers to the railsbridge/docs repo if they did get merged together.

I'm sure there are some pros/cons that I'm missing, so let me know what you think!

**Comment by mxie** [comment]
Hey @lilliealbert - We definitely have the intention of merging with railsbridge/docs, but it's currently proving difficult because this repo is not an "official fork" (see #23). I think once we sort this out, we can move forward with the merge. In the mean time, making a few of us as committers would be great!

**Comment by pcai** [comment]
fixed now, see #23
